
# /home/simon/otitenet/otitenet/app/pages/new_analysis.py

from __future__ import annotations

import copy
import os
import time
import traceback
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import streamlit as st

from otitenet.app.analysis import run_analysis_on_file
from otitenet.app.display_metrics import _arrow_safe_dataframe
from otitenet.app.utils import (
    format_classifier_config,
    resolve_best_classifier_config,
    strip_extension,
)


IMAGE_TYPES = ["jpg", "jpeg", "png", "bmp", "tif", "tiff"]


def _fmt_confidence(value) -> str:
    try:
        return f"{float(value):.2f}"
    except Exception:
        return ""


def _normalize_analysis_result(result):
    """
    Accept old/new run_analysis_on_file return shapes.

    Known shapes:
    - (pred_label, confidence, log_path, existing)
    - (pred_label, confidence, log_path, existing, gradcam_path)
    - variants with extra values appended
    """
    if not isinstance(result, (tuple, list)):
        raise ValueError(f"run_analysis_on_file returned unsupported type: {type(result)}")

    if len(result) < 2:
        raise ValueError(f"run_analysis_on_file returned too few values: {len(result)}")

    pred_label = result[0]
    confidence = result[1]
    complete_log_path = result[2] if len(result) > 2 else None
    existing = result[3] if len(result) > 3 else None
    gradcam_path = result[4] if len(result) > 4 else None

    return pred_label, confidence, complete_log_path, existing, gradcam_path


def _clone_args(args):
    try:
        return copy.copy(args)
    except Exception:
        return args


def _current_head_config(args):
    """
    Resolve the active learned-embedding classifier head.

    Priority:
    1. Explicit sidebar selection
    2. args.best_classifier_config
    3. best cached/optimized head
    4. args.n_neighbors fallback
    """
    explicit = st.session_state.get("sidebar_classification_head_config")
    if explicit is not None and str(explicit).strip() not in {"", "None", "nan"}:
        return str(explicit)

    existing = getattr(args, "best_classifier_config", None)
    if existing is not None and str(existing).strip() not in {"", "None", "nan"}:
        return str(existing)

    try:
        return str(resolve_best_classifier_config(args, use_optimized=True))
    except Exception:
        return str(getattr(args, "n_neighbors", 1))


def _set_head_on_args(args, head_config):
    if head_config is None:
        return args

    args.best_classifier_config = str(head_config)
    args.learned_classifier_label = format_classifier_config(head_config)

    try:
        if str(head_config).isdigit():
            args.n_neighbors = int(head_config)
    except Exception:
        pass

    return args


def _prepare_analysis_args(ctx, infer_method: str, dist_metric: str):
    args = _clone_args(ctx.args)

    args.infer_method = infer_method
    args.dist_metric = dist_metric

    head_config = _current_head_config(args)
    _set_head_on_args(args, head_config)

    return args, head_config


def _delete_existing_results_for_files(ctx, filenames: List[str]) -> None:
    """
    Remove existing rows for the current person/model/files before a forced analysis.

    run_analysis_on_file usually handles force_reanalyze, but this prevents old
    duplicate rows if old schemas/logic allowed duplicates.
    """
    if not filenames:
        return

    person_id = st.session_state.get("person_id") or getattr(ctx, "selected_person_id", None)
    model_id = getattr(ctx.args, "model_id", None) or st.session_state.get("selected_model_params", {}).get("model_id")

    if person_id is None or model_id is None:
        return

    placeholders = ",".join(["%s"] * len(filenames))

    try:
        ctx.cursor.execute(
            f"""
            DELETE FROM results
            WHERE person_id=%s AND model_id=%s AND filename IN ({placeholders})
            """,
            tuple([int(person_id), model_id] + list(filenames)),
        )
        ctx.conn.commit()
    except Exception:
        try:
            ctx.conn.rollback()
        except Exception:
            pass


def _find_gradcam_images(log_path: str, filename: str, n_layers: int = 4) -> List[str]:
    """
    Find Grad-CAM composite images generated by analysis.py.

    Expected layout:
      <log_path>/<base>/<base>_grad_cam_all_classes_layerX.png
    """
    if not log_path or not filename:
        return []

    import glob
    import re

    base = strip_extension(os.path.basename(str(filename)))
    root = os.path.join(str(log_path), base)

    patterns = [
        os.path.join(root, f"{base}_grad_cam_all_classes_layer*.png"),
        os.path.join(root, f"*{base}*grad*cam*layer*.png"),
        os.path.join(str(log_path), "**", f"{base}_grad_cam_all_classes_layer*.png"),
    ]

    found = []
    for pattern in patterns:
        try:
            found.extend(glob.glob(pattern, recursive=True))
        except Exception:
            pass

    found = [p for p in found if os.path.isfile(p)]
    found = list(dict.fromkeys(found))

    def layer_key(path):
        match = re.search(r"layer(\d+)", os.path.basename(str(path)).lower())
        return int(match.group(1)) if match else -1

    found = sorted(found, key=layer_key, reverse=True)
    return found[: int(n_layers)]


def _render_uploaded_previews(uploaded_files) -> None:
    if not uploaded_files:
        return

    with st.expander("Uploaded image preview", expanded=len(uploaded_files) <= 3):
        cols_per_row = 3
        for start in range(0, len(uploaded_files), cols_per_row):
            cols = st.columns(cols_per_row)
            for col, file_obj in zip(cols, uploaded_files[start : start + cols_per_row]):
                with col:
                    try:
                        st.image(file_obj, caption=file_obj.name, use_container_width=True)
                    except Exception:
                        st.caption(file_obj.name)


def _render_results_table(results: List[Dict[str, Any]]) -> None:
    if not results:
        return

    df = pd.DataFrame(results)

    display_cols = [
        "Filename",
        "Prediction",
        "Confidence",
        "Existing",
        "Grad-CAM",
        "Log Path",
        "Elapsed (s)",
    ]
    display_cols = [c for c in display_cols if c in df.columns]

    table = df[display_cols].copy()

    if "Confidence" in table.columns:
        table["Confidence"] = table["Confidence"].apply(_fmt_confidence)

    st.subheader("Analysis results")
    st.dataframe(_arrow_safe_dataframe(table.drop(columns=["Log Path"], errors="ignore")), use_container_width=True)


def _render_single_result_observer(results: List[Dict[str, Any]], n_layers: int = 4) -> None:
    if not results:
        return

    st.subheader("Observe result")

    options = list(range(len(results)))

    def option_label(i):
        r = results[i]
        return f"{r.get('Filename')} | pred={r.get('Prediction')} | conf={_fmt_confidence(r.get('Confidence'))}"

    selected = st.selectbox(
        "Select analyzed image",
        options=options,
        format_func=option_label,
        key="new_analysis_observe_result",
    )

    row = results[selected]

    c1, c2 = st.columns([1, 1])

    with c1:
        file_bytes = row.get("Bytes")
        if file_bytes:
            st.image(file_bytes, caption=f"Input: {row.get('Filename')}", use_container_width=True)

    with c2:
        st.markdown(f"**Prediction:** {row.get('Prediction')}")
        st.markdown(f"**Confidence:** {_fmt_confidence(row.get('Confidence'))}")
        st.markdown(f"**Existing cached result:** {row.get('Existing')}")
        if row.get("Log Path"):
            with st.expander("Log path"):
                st.code(str(row.get("Log Path")))

    gradcam_images = _find_gradcam_images(row.get("Log Path"), row.get("Filename"), n_layers=n_layers)

    if gradcam_images:
        st.markdown("**Grad-CAM**")
        for path in gradcam_images:
            st.image(path, caption=os.path.basename(path), use_container_width=True)
    elif row.get("Grad-CAM Path"):
        st.info(f"Grad-CAM path returned: {row.get('Grad-CAM Path')}")
    else:
        st.info(
            "No Grad-CAM montage found yet. Fresh predictions should generate Grad-CAM automatically. "
            "Try Force New Analysis if this result was loaded from cache."
        )


def _render_current_model_summary(args, head_config, is_admin: bool) -> None:
    st.subheader("Current analysis model")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.markdown(f"**Model:** {getattr(args, 'model_name', '—')}")
        st.markdown(f"**Size:** {getattr(args, 'new_size', '—')}")
        st.markdown(f"**Normalize:** {getattr(args, 'normalize', '—')}")

    with c2:
        st.markdown(f"**Loss:** {getattr(args, 'classif_loss', '—')}")
        st.markdown(f"**DLoss:** {getattr(args, 'dloss', '—')}")
        st.markdown(f"**Distance:** {getattr(args, 'dist_fct', '—')}")

    with c3:
        st.markdown(f"**Head:** {format_classifier_config(head_config)}")
        st.markdown(f"**n_neighbors:** {getattr(args, 'n_neighbors', '—')}")
        st.markdown(f"**Mode:** {'admin-selected model' if is_admin else 'production model'}")


def render(ctx):
    st.header("🧪 New Analysis")

    selected_person_id = (
        st.session_state.get("person_id")
        or getattr(ctx, "selected_person_id", None)
    )

    if selected_person_id is None:
        st.warning("Please create or select a family member from the sidebar before running a new analysis.")
        return

    st.session_state["person_id"] = selected_person_id

    is_admin = bool(getattr(ctx, "is_admin", False))

    if not is_admin and not st.session_state.get("production_model"):
        st.warning("No production model is currently selected by the admin.")
        return

    uploaded_files = st.file_uploader(
        "Upload one or more otoscope images",
        type=IMAGE_TYPES,
        accept_multiple_files=True,
        key="new_analysis_uploaded_files",
    )

    if uploaded_files:
        _render_uploaded_previews(uploaded_files)

    st.divider()

    if is_admin:
        st.subheader("Inference settings")

        infer_method = st.selectbox(
            "Inference Method",
            options=["majority_vote", "prototypes", "prototype_distance"],
            index=0,
            help=(
                "majority_vote: learned classifier / KNN-style output. "
                "prototypes: direct prototype distance. "
                "prototype_distance: inverse distance ratio."
            ),
            key="new_analysis_infer_method",
        )

        if infer_method == "prototype_distance":
            dist_metric = st.selectbox(
                "Distance Metric",
                options=["euclidean", "cosine"],
                index=0,
                key="new_analysis_dist_metric",
            )
        else:
            dist_metric = "euclidean"

        c_speed1, c_speed2, c_speed3 = st.columns(3)

        with c_speed1:
            skip_validation = st.checkbox(
                "⚡ Skip validation metrics",
                value=False,
                help="Skip loading validation metrics to speed up inference.",
                key="new_analysis_skip_validation",
            )

        with c_speed2:
            fast_infer = st.checkbox(
                "⚡ Fast inference",
                value=False,
                help="Use faster inference path where supported.",
                key="new_analysis_fast_infer",
            )

        with c_speed3:
            n_gradcam_layers = st.number_input(
                "Grad-CAM layers to display",
                min_value=1,
                max_value=10,
                value=4,
                step=1,
                key="new_analysis_gradcam_layers",
            )

        force_reanalyze = st.checkbox(
            "🔄 Force New Analysis",
            value=False,
            key="new_analysis_force_reanalyze",
        )

    else:
        infer_method = "majority_vote"
        dist_metric = "euclidean"
        skip_validation = True
        fast_infer = False
        n_gradcam_layers = 4
        force_reanalyze = False

        st.caption(
            "Client mode uses the admin-selected production model. "
            "If the production model changed, a new result is computed; otherwise the saved result may be loaded."
        )

    analysis_args, head_config = _prepare_analysis_args(ctx, infer_method, dist_metric)
    _render_current_model_summary(analysis_args, head_config, is_admin=is_admin)

    if uploaded_files and len(uploaded_files) > 1:
        st.info(f"Batch mode: {len(uploaded_files)} files will be processed.")

    st.divider()

    run_clicked = st.button(
        "▶️ Run Analysis",
        key="new_analysis_run",
        disabled=not bool(uploaded_files),
        type="primary",
    )

    if not run_clicked:
        previous_results = st.session_state.get("new_analysis_last_results", [])
        if previous_results:
            _render_results_table(previous_results)
            _render_single_result_observer(previous_results, n_layers=int(n_gradcam_layers))
        return

    filenames = [os.path.basename(f.name) for f in uploaded_files]

    if force_reanalyze:
        _delete_existing_results_for_files(ctx, filenames)

    progress_bar = st.progress(0.0)
    status_text = st.empty()
    results = []
    start_time = time.time()

    for idx, file_obj in enumerate(uploaded_files):
        file_start = time.time()
        filename = os.path.basename(file_obj.name)

        status_text.write(f"Processing {idx + 1}/{len(uploaded_files)}: {filename}")
        progress_bar.progress(idx / max(len(uploaded_files), 1))

        try:
            file_bytes = file_obj.read()
            file_obj.seek(0)

            result = run_analysis_on_file(
                filename,
                file_bytes,
                analysis_args,
                ctx.cursor,
                ctx.conn,
                force_reanalyze=force_reanalyze,
                show_validation_metrics=not skip_validation,
                fast_infer=fast_infer,
            )

            pred_label, confidence, complete_log_path, existing, gradcam_path = _normalize_analysis_result(result)

            gradcam_images = _find_gradcam_images(
                complete_log_path,
                filename,
                n_layers=int(n_gradcam_layers),
            )

            results.append(
                {
                    "Filename": filename,
                    "Prediction": pred_label,
                    "Confidence": confidence,
                    "Existing": existing,
                    "Log Path": complete_log_path,
                    "Grad-CAM Path": gradcam_path,
                    "Grad-CAM": len(gradcam_images),
                    "Elapsed (s)": round(time.time() - file_start, 2),
                    "Bytes": file_bytes,
                }
            )

            st.session_state["last_uploaded_name"] = filename
            st.session_state["last_complete_log_path"] = complete_log_path
            st.session_state["last_prediction"] = pred_label
            st.session_state["last_confidence"] = confidence

        except Exception as e:
            results.append(
                {
                    "Filename": filename,
                    "Prediction": "ERROR",
                    "Confidence": None,
                    "Existing": False,
                    "Log Path": None,
                    "Grad-CAM": 0,
                    "Elapsed (s)": round(time.time() - file_start, 2),
                    "Error": str(e),
                    "Bytes": None,
                }
            )

            with st.expander(f"Error details for {filename}"):
                st.code(traceback.format_exc())

        progress_bar.progress((idx + 1) / max(len(uploaded_files), 1))

    status_text.success(f"Finished {len(uploaded_files)} file(s) in {time.time() - start_time:.1f}s.")

    st.session_state["new_analysis_last_results"] = results

    _render_results_table(results)

    error_rows = [r for r in results if r.get("Prediction") == "ERROR"]
    if error_rows:
        st.warning(f"{len(error_rows)} file(s) failed.")

    st.divider()
    _render_single_result_observer(results, n_layers=int(n_gradcam_layers))